In [12]:
import numpy as np 
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b=np.arange(10)**3
b

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [23]:
b[2] 

8

In [22]:
b[2:5] # index 2 is the starting point and index 5 is the ending point where last index is 4

array([ 8, 27, 64])

In [33]:
a=np.arange(100,5,-2) # start val is 100 and decrement by -2 until index of greater than 5
a

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6])

In [5]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
a
#this resize the ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
# we can use reshape funtion
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
#slice item from starting index
#https://www.tutorialspoint.com/numpy/numpy_indexing_and_slicing.htm
a=np.arange(10)
print(a[2:]) 

[2 3 4 5 6 7 8 9]


In [14]:
#slice item   between index
a=np.arange(10)
print(a[2:8])


[2 3 4 5 6 7]


In [18]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a
print("we will slice the item from the index a[1:] which is second row of the array")
print(a[1:])

we will slice the item from the index a[1:] which is second row of the array
[[4 5 6]
 [7 8 9]]


In [19]:
# new array
import numpy as np
item=np.array([[1,20,30],[40,50,60],[70,80,90]])
print("our array is : \n")
print(item)

our array is : 

[[ 1 20 30]
 [40 50 60]
 [70 80 90]]


In [22]:
#this return the item in the second column
print(item[...,1])
print('\n')

[20 50 80]




In [23]:
#this return the item in the third column
print(item[...,2])
print('\n')

[30 60 90]




In [24]:
#this return the item in the second row
print(item[1,...])
print('\n')

[40 50 60]




In [25]:
#this return the item in the first row
print(item[0,...])
print('\n')

[ 1 20 30]




In [34]:
# Now we will slice all items from first row  0 onwards
print(item[0:,...])
print('\n')

[[ 1 20 30]
 [40 50 60]
 [70 80 90]]




In [35]:
# Now we will slice all items from second row  1 onwards
print(item[1:,...])
print('\n')

[[40 50 60]
 [70 80 90]]




In [28]:
# Now we will slice all items from second column  1 onwards
print(item[...,1:])
print('\n')

[[20 30]
 [50 60]
 [80 90]]




In [36]:
# Now we will slice all items from first column  0 onwards
print(item[...,0:])
print('\n')

[[ 1 20 30]
 [40 50 60]
 [70 80 90]]




In [32]:
# Now we will slice all items from last column   backwards
print(item[...,-3:])
print('\n')

[[ 1 20 30]
 [40 50 60]
 [70 80 90]]




In [37]:
# Now we will slice all items from last column   backwards
print(item[...,-1:])
print('\n')

[[30]
 [60]
 [90]]


