In [5]:
import numpy as np

a=np.arange(15).reshape(3,5)
a
# here 3 row and 5 column will be print

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape


(3, 5)

In [7]:
a.ndim

2

In [8]:
a.dtype.name

'int64'

In [9]:
a.itemsize

8

In [10]:
a.size

15

In [11]:
type(a)

numpy.ndarray

In [12]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [15]:
np.zeros((3,4),dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [16]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [51]:
np.arange(10,30,5) # start value is 10 and increment by 5 less than 30

array([10, 15, 20, 25])

In [18]:
np.arange(10,30,4)

array([10, 14, 18, 22, 26])

In [19]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [20]:
np.arange(10,30,-1)

array([], dtype=int64)

In [21]:
np.arange(10,30,.5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. ,
       26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

In [29]:
np.linspace(0,15,5) # rule: (15-Firstval)/4

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [54]:
np.linspace(10,15,5) #rule :(15-10)/4

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

In [53]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [31]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [33]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
c

array([20, 29, 38, 47])

In [34]:
b**2

array([0, 1, 4, 9])

In [35]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [36]:
a<35

array([ True,  True, False, False])

In [37]:
a*b


array([  0,  30,  80, 150])

In [40]:
b=np.random.random((2,3))
b

array([[0.22959274, 0.29424483, 0.74231025],
       [0.97313207, 0.3135893 , 0.50968005]])

In [47]:
c=np.random.random((2,3))
c

array([[0.1573922 , 0.26607018, 0.97781774],
       [0.74053453, 0.45140705, 0.59506671]])

In [48]:
c.sum()

3.188288413460771

In [49]:
c.max()

0.9778177366205486

In [50]:
c.min()

0.15739220293221223